CREATE TABLE teams (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                VARCHAR(64)  NOT NULL UNIQUE,
    name                VARCHAR(200) NOT NULL,
    slogan              VARCHAR(500) NOT NULL,
    accent              VARCHAR(20)  NOT NULL,
    president_name      VARCHAR(200) NOT NULL,
    president_dept      VARCHAR(200) NOT NULL,
    president_initials  VARCHAR(10)  NOT NULL,
    vp_name             VARCHAR(200) NOT NULL,
    vp_dept             VARCHAR(200) NOT NULL,
    vp_initials         VARCHAR(10)  NOT NULL,
    vision              TEXT         NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE pillars (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id     BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    icon        VARCHAR(16)   NOT NULL,
    title       VARCHAR(200)  NOT NULL,
    description TEXT          NOT NULL,
    sort_order  INT           NOT NULL
);
CREATE INDEX idx_pillars_team_id ON pillars(team_id);

CREATE TABLE initiatives (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id     BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    headline    VARCHAR(300)  NOT NULL,
    detail      TEXT          NOT NULL,
    sort_order  INT           NOT NULL
);
CREATE INDEX idx_initiatives_team_id ON initiatives(team_id);

CREATE TABLE votes (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id  BIGINT NOT NULL REFERENCES teams(id),
    cast_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_votes_team_id ON votes(team_id);
