CREATE TABLE verification_codes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_hash    VARCHAR(64) NOT NULL UNIQUE,
    team_id       BIGINT      NOT NULL REFERENCES teams(id),
    code_hash     VARCHAR(64) NOT NULL,
    attempts      INT         NOT NULL DEFAULT 0,
    expires_at    TIMESTAMPTZ NOT NULL,
    last_sent_at  TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE voter_records (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_hash  VARCHAR(64) NOT NULL UNIQUE,
    voted_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
