spring.datasource.url=jdbc:postgresql://localhost:5433/msavoting
spring.datasource.username=msavoting
spring.datasource.password=msavoting

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

app.election.total-eligible-voters = 160
app.cors.allowed-origins=http://localhost:5173, https://hanyang-msa-voting.vercel.app